# Generated by Django 3.1.3 on 2020-12-02 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название базы данных')),
                ('document', models.FileField(upload_to='documents/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('project', models.CharField(max_length=5, verbose_name='Название проекта')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('available_numbers', models.IntegerField(verbose_name='Всего номеров получено')),
                ('used', models.IntegerField(verbose_name='Номеров использовано')),
                ('remainder', models.IntegerField(verbose_name='Остаток')),
                ('source', models.CharField(max_length=50, verbose_name='Источник')),
                ('how_collected', models.CharField(max_length=255, verbose_name='Способ получения')),
                ('responsible', models.CharField(max_length=255, verbose_name='Ответственный')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('status', models.CharField(blank=True, max_length=5, verbose_name='Статус')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('price_per_number', models.FloatField(verbose_name='Цена за каждый номер')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='import_db.document', verbose_name='Имя загруженного файла')),
            ],
        ),
    ]
